#UI Settings
[UX]
	#The maximum length (in pixels) a button may be. This effects the rendering of the button texture.
	max_button_length = 200
	#The default width of widgets.
	default_widget_width = 200
	#The default height of widgets.
	default_widget_height = 20

#Client only settings. These should only be modified by experienced users.
[Debug]
	#Enable debug mode. Don't enable this.
	debug = true
	#Debug color
	color = 671142400