modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory (26 is current forge version)
#issueTrackerURL="http://my.issue.tracker/" #optional
#logoFile="examplemod.png" #optional

[[mods]] #mandatory
# The modid of the mod
modId="admintools" #mandatory
version="${version}" #mandatory
displayName="Admin Tools" #mandatory
#updateJSONURL="https://www.google.com" #optional
#displayURL="" #optional

#credits="" #
authors="Senmori"
description='''
A library to make it easier to make guis
'''